### create user

POST http://localhost:8080/users HTTP/1.1
content-type: application/json

{
    "username": "azamat3",
    "email": "azamat4@email.com",
    "full_name": "azamat azamat",
    "password": "qwerty123"
}

###
        
### login user

POST http://localhost:8080/users/login HTTP/1.1
content-type: application/json

{
    "username": "azamat3",
    "password": "qwerty123"
}

###

### create an account

POST http://localhost:8080/accounts HTTP/1.1
content-type: application/json

{
    "owner": "Someone",
    "currency": "EUR"
}
###

### get one account

GET http://localhost:8080/accounts/207 HTTP/1.1

###


### list accounts

GET http://localhost:8080/accounts
        ?page_id=0
        &page_size=20 HTTP/1.1
        
###


### create transfer

POST http://localhost:8080/transfers HTTP/1.1
content-type: application/json

{
    "from_account_id": 1,
    "to_account_id": 2,
    "amount": 100,
    "currency": "USD"
}
        
###

